package mvz2.modding;

import mvz2.map.MapModel;
import mvz2.metas.AchievementMetaList;
import mvz2.metas.AlmanacMetaList;
import mvz2.metas.ArcadeMetaList;
import mvz2.metas.AreaMetaList;
import mvz2.metas.ArmorMetaList;
import mvz2.metas.ArtifactMetaList;
import mvz2.metas.BlueprintMetaList;
import mvz2.metas.BuffMetaList;
import mvz2.metas.ChapterTransitionMetaList;
import mvz2.metas.CommandMetaList;
import mvz2.metas.CreditMetaList;
import mvz2.metas.DifficultyMetaList;
import mvz2.metas.EntityMetaList;
import mvz2.metas.FragmentMetaList;
import mvz2.metas.GridMetaList;
import mvz2.metas.MainmenuViewMetaList;
import mvz2.metas.MapMetaList;
import mvz2.metas.ModelMetaList;
import mvz2.metas.MusicMetaList;
import mvz2.metas.NoteMetaList;
import mvz2.metas.OptionMetaList;
import mvz2.metas.ProgressBarMetaList;
import mvz2.metas.ShapeMetaList;
import mvz2.metas.SoundMetaList;
import mvz2.metas.SpawnMetaList;
import mvz2.metas.StageMetaList;
import mvz2.metas.StatMetaList;
import mvz2.metas.StoreMetaList;
import mvz2.metas.TalkCharacterMetaList;
import mvz2.metas.UnlockMetaList;
import mvz2.models.AreaModel;
import mvz2.models.Model;
import mvz2.talkdata.CharacterVariantSprites;
import mvz2.talkdata.TalkMeta;
import unity.AudioClip;
import unity.Sprite;
import mvz2.metas.ArchiveMetaList;
import mvz2.talkdata.CharacterVariantSprites.CharacterVariantSprite;

// Ported from: Assets/Scripts/MVZ2/Modding/ModResource.cs
class ModResource {
    public var Namespace:String;
    public var SoundMetaList:SoundMetaList;
    public var ModelMetaList:ModelMetaList;
    public var FragmentMetaList:FragmentMetaList;
    public var TalkCharacterMetaList:TalkCharacterMetaList;
    public var DifficultyMetaList:DifficultyMetaList;
    public var ArmorMetaList:ArmorMetaList;
    public var EntityMetaList:EntityMetaList;
    public var CommandMetaList:CommandMetaList;
    public var ShapeMetaList:ShapeMetaList;
    public var ArtifactMetaList:ArtifactMetaList;
    public var AlmanacMetaList:AlmanacMetaList;
    public var NoteMetaList:NoteMetaList;
    public var StageMetaList:StageMetaList;
    public var MapMetaList:MapMetaList;
    public var AreaMetaList:AreaMetaList;
    public var StatMetaList:StatMetaList;
    public var AchievementMetaList:AchievementMetaList;
    public var StoreMetaList:StoreMetaList;
    public var MusicMetaList:MusicMetaList;
    public var ArchiveMetaList:ArchiveMetaList;
    public var MainmenuViewMetaList:MainmenuViewMetaList;
    public var ProgressBarMetaList:ProgressBarMetaList;
    public var BlueprintMetaList:BlueprintMetaList;
    public var SpawnMetaList:SpawnMetaList;
    public var GridMetaList:GridMetaList;
    public var CreditsMetaList:CreditMetaList;
    public var ChapterTransitionMetaList:ChapterTransitionMetaList;
    public var ArcadeMetaList:ArcadeMetaList;
    public var BuffMetaList:BuffMetaList;
    public var UnlockMetaList:UnlockMetaList;
    public var OptionMetaList:OptionMetaList;
    public var Sounds:Map<String, AudioClip> = new Map();
    public var Musics:Map<String, AudioClip> = new Map();
    public var SpriteSheets:Map<String, Array<Sprite>> = new Map();
    public var Sprites:Map<String, Sprite> = new Map();
    public var CharacterVariantSprites:Map<String, Array<CharacterVariantSprite>> = new Map();
    public var TalkMetas:Map<String, TalkMeta> = new Map();
    public var MapModels:Map<String, MapModel> = new Map();
    public var AreaModels:Map<String, AreaModel> = new Map();
    public var Models:Map<String, Model> = new Map();
    public var ModelIcons:Map<String, Sprite> = new Map();
    public function new(spaceName:String) {
        Namespace = spaceName;
    }
}
